# Site name
site_name: "Ingwane Labs ~ Site Status" 
dev_addr: '0.0.0.0:8000'

# Navigation menu
nav:
  - Status Updates:
    - "Today ~ 2025/21-320": message-202521320.md
    - "Today ~ 2025/21-430": message-202521430.md

  - Planned Maintenance:
    - "December 8, 2025": planned-20251208.md

  - Mailbox: mailbox.md

  - Resources:
    - response-template.md

# Existing files but not in nav
not_in_nav: |
  index.md

# Theme
theme:
 name: material
 palette:
    primary: red
    accent: red
 icon:
   logo: material/fire
 features:
   - toc.integrate 

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: false
      toc_depth: 1
