# Site name
site_name: "Ingwane Labs ~ Site Status" 
dev_addr: '0.0.0.0:8000'

# Navigation menu
nav:
  - Status Updates:
    - index.md

# Theme
theme:
 name: material
 palette:
    primary: red
    accent: red
 icon:
   logo: material/fire
features:
    - toc.integrate

# Extensions
markdown_extensions:
  - toc:
      permalink: true
