# Site name
site_name: "Ingwane Labs ~ Site Status" 
dev_addr: '0.0.0.0:8000'

# Navigation menu
nav:
  - Status Updates:
    - index.md

# Existing files but not in nav
not_in_nav: |
  thursday-1445.md

# Theme
theme:
 name: material
 palette:
    primary: red
    accent: red
 icon:
   logo: material/fire
