# Site name
site_name: "Ingwane Labs ~ Site Status" 
dev_addr: '0.0.0.0:8000'

# Navigation menu
nav:
  - Status Updates:
    - "Tuesday, 1:20 PM": tuesday-1320.md

  - Planned Maintenance:
    - "August 8, 2025": planned-20250808.md

  - Resources:
    - response-template.md

# Existing files but not in nav
not_in_nav: |
  index.md
  tuesday-1430.md

# Theme
theme:
 name: material
 palette:
    primary: red
    accent: red
 icon:
   logo: material/fire
 features:
   - toc.integrate 

# Extensions
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 1

