# Site name
site_name: "Ingwane Labs ~ Site Status" 
dev_addr: '0.0.0.0:8000'

# Navigation menu
nav:
  - Status Updates:
    - thursday-1345.md

  - Resources:
    - response-template.md

# Existing files but not in nav
not_in_nav: |
  thursday-1445.md

# Theme
theme:
 name: material
 palette:
    primary: red
    accent: red
 icon:
   logo: material/fire
 features:
   - navigation.expand
   - toc.integrate 

# Extensions
markdown_extensions:
  - toc:
      permalink: true
